project:
  type: website
  output-dir: docs

website:
  title: "Madeleine Potter"
  navbar:
    right:
      - about.qmd
      - resume.qmd
      - icon: github
        href: https://github.com/madeleinepotter
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

